name: Run Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make run.sh executable
        run: chmod +x run.sh

      - name: Run run.sh
        run: ./run.sh
